name: tests
run-name: tests
on:
  workflow_call:

  push:
    branches:
      - "**"
jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python_version: ['3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - run: pip install -r requirements.txt
      - run: tox